export const CART_ACTION_TYPES = {
  SET_CART_IS_ACTIVE: "cart/SET_CART_IS_OPEN",
  SET_CART_COUNT: "cart/SET_CART_COUNT",
  SET_CART_TOTAL: "cart/SET_CART_TOTAL",
  SET_CART_ITEMS: "cart/SET_CART_ITEMS",
};
